import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThirdwebProvider, ChainId } from "@thirdweb-dev/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nero Drop",
  description: "Generated by create next app",
};

const activeChainId = ChainId.Sepolia;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider desiredChainId={activeChainId}>
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
